"""
Remark corpus for SATARK synthetic data generation.
400+ UPI remark templates across 8 fraud categories and legitimate transactions.
Imported by 01_generate_synthetic_data.py.
"""

LEGITIMATE = [
    "rent march", "rent april", "rent may", "rent payment", "house rent",
    "zomato order", "swiggy order", "food order", "dinner payment",
    "amazon refund", "flipkart refund", "meesho refund", "return payment",
    "bhai ka birthday", "didi gift", "birthday gift", "anniversary gift",
    "grocery settlement", "kirana dukan", "sabzi wala", "grocery bill",
    "EMI payment", "loan emi", "bike emi", "car emi", "home loan emi",
    "electricity bill", "bijli bill", "light bill", "current bill",
    "water bill", "gas bill", "piped gas", "png bill",
    "broadband bill", "internet payment", "wifi bill", "jio fiber",
    "mobile recharge", "prepaid recharge", "sim recharge", "number recharge",
    "petrol", "fuel", "petrol money", "diesel",
    "tea paise", "chai coffee", "canteen", "lunch",
    "sharma ji", "verma bhai", "gupta sahab", "joshi uncle",
    "tuition fees", "coaching fees", "class fees", "school fees",
    "medicine", "pharmacy", "dawa", "chemist",
    "doctor fees", "hospital payment", "clinic fees",
    "train ticket", "bus ticket", "flight ticket", "travel",
    "movie tickets", "bookmyshow", "inox", "pvr",
    "gym fees", "yoga class", "fitness payment",
    "salary advance", "advance payment", "pending dues",
    "parking fees", "toll payment",
    "furniture payment", "sofa advance", "table delivery",
    "stitching charges", "tailor payment", "kapde wala",
    "newspaper", "dhobi", "laundry",
    "plumber charges", "electrician fees", "carpenter payment",
    "cricket bet settlement", "card game", "friendly match",
    "borrow return", "udhar wapas", "paise wapas", "loan return",
    "transfer", "payment", "send", "money", "paise",
    "reimbursement", "refund", "return", "cashback transfer",
    "share market", "mutual fund top up", "fd deposit",
    "insurance premium", "lic premium", "term plan",
    "vegetable", "milk payment", "dairy", "amul",
    "courier charges", "delivery charges", "shipping",
    "birthday treat", "party payment", "celebration",
    "trip advance", "vacation payment", "hotel booking",
    "ac repair", "fridge repair", "washing machine service",
    "laptop repair", "mobile screen repair",
    "book purchase", "stationary", "pen notebook",
    "donation", "temple donation", "charity",
    "wedding gift", "shaadi gift", "engagement gift",
    "house warming", "griha pravesh gift",
    "exam fees", "university fees", "hostel fees",
    "mess fees", "canteen advance", "tiffin payment",
    "painting advance", "whitewash payment",
    "security deposit", "advance deposit", "token money",
    "split bill", "bill split", "dinner split", "outing split",
    "recharge dena tha", "paise bhej raha hoon", "le lo",
    "thanks bhai", "help ke liye", "teri madad",
]

KYC_SCAM = [
    "electricity KYC penalty avoid disconnection",
    "bijli KYC update fee disconnection bachao",
    "electricity board KYC verification charge",
    "power supply KYC penalty last date",
    "gas connection KYC update fee",
    "png gas KYC verification charge",
    "piped gas KYC penalty payment",
    "indane gas KYC fee urgent",
    "SIM card KYC verification charge",
    "mobile number KYC update penalty",
    "jio sim KYC fee disconnection",
    "airtel KYC update charge urgent",
    "vi vodafone KYC penalty fee",
    "Aadhaar update processing fee",
    "aadhaar KYC link bank account fee",
    "aadhaar verification penalty payment",
    "pan card KYC link fee",
    "pan aadhaar link penalty charge",
    "bank account KYC update fee",
    "bank KYC verification penalty urgent",
    "account freeze avoid KYC fee",
    "SBI KYC update charge",
    "HDFC KYC penalty payment",
    "ICICI bank KYC fee urgent",
    "debit card KYC verification fee",
    "credit card KYC update penalty",
    "UPI KYC verification charge",
    "UPI limit increase KYC fee",
    "wallet KYC verification penalty",
    "paytm KYC update fee urgent",
    "phonepe KYC verification charge",
    "electricity meter KYC fee",
    "smart meter KYC update penalty",
    "LPG connection KYC fee",
    "cylinder booking KYC verification charge",
    "broadband KYC update fee",
    "internet connection KYC penalty",
    "DTH KYC verification charge",
    "tata sky KYC fee disconnection avoid",
    "bijli KYC penalty kal last date",
    "kyc update fee electricity board",
    "bijli KYC nahi kiya toh katega",
    "sim kyc update nahi toh band hoga",
    "bank kyc penalty fees urgent payment",
    "kyc verification fee government",
    "aadhar kyc update penalty avoidance fee",
    "bses KYC penalty payment urgent",
    "mseb KYC update fee last chance",
    "electricity disconnection avoid KYC payment",
    "gas KYC penalty fee today only",
]

LOTTERY_SCAM = [
    "prize claim processing fee",
    "KBC winner processing fee",
    "lottery claim advance payment",
    "winning amount release fee",
    "KBC lottery winner fee",
    "prize money processing charge",
    "lucky draw winner advance",
    "lottery ticket claim fee",
    "jackpot claim processing",
    "prize verification fee urgent",
    "government lottery winner fee",
    "state lottery claim charge",
    "bumper lottery processing fee",
    "KBC 25 lakh claim fee",
    "lottery prize tax payment advance",
    "winner certificate processing fee",
    "prize delivery charge advance",
    "lucky winner verification fee",
    "online lottery winner fee",
    "lucky draw first prize claim",
    "jeet ka inam processing",
    "prize lene ke liye fee",
    "lottery winner advance payment",
    "bumper prize claim advance",
    "KBC winner advance bhej do",
    "prize claim karne ke liye paise",
    "inam claim processing fee",
    "lucky winner advance required",
    "scratch card prize claim fee",
    "WhatsApp lottery winner fee",
]

TECH_SUPPORT_SCAM = [
    "refund processing fee helpdesk",
    "Amazon refund initiation fee",
    "flipkart refund processing charge",
    "laptop warranty refund charge",
    "Microsoft refund processing fee",
    "computer virus removal fee",
    "PC repair remote charge",
    "antivirus renewal fee urgent",
    "tech support refund verification",
    "Amazon seller refund advance",
    "bank refund processing fee",
    "refund activation charge",
    "insurance refund processing fee",
    "cashback processing fee advance",
    "refund transaction verification fee",
    "helpdesk support charge",
    "customer care refund fee",
    "toll free call refund processing",
    "OTP verification refund fee",
    "refund bounce fee payment",
    "Amazon refund pending activation",
    "flipkart cashback unlock fee",
    "refund processing paise bhejo",
    "customer helpdesk refund advance",
    "tech support verification charge urgent",
    "refund de rahe hain fee bhejo",
    "amazon wale refund denge fee bhejo",
    "refund ke liye verification fee",
]

IMPERSONATION_SCAM = [
    "CBI officer case settlement fee",
    "income tax penalty payment",
    "customs clearance fee urgent",
    "police station verification fee",
    "court case settlement advance",
    "FIR settlement fee",
    "case band karne ke liye fee",
    "income tax notice penalty payment",
    "IT department penalty fee",
    "customs duty clearance advance",
    "drug case settlement fee",
    "CBI case clearance payment",
    "arrest warrant settlement fee",
    "cyber crime case settlement",
    "police NOC fee urgent",
    "government penalty clearance fee",
    "tax evasion settlement payment",
    "legal notice settlement advance",
    "court order compliance fee",
    "enforcement directorate settlement",
    "ED case clearance fee",
    "TRAI disconnection penalty fee",
    "telecom penalty payment urgent",
    "illegal transaction penalty fee",
    "RBI penalty compliance payment",
    "SEBI penalty settlement advance",
    "income tax demand notice payment",
    "police case band karne ke paise",
    "CBI ne case kiya settlement fee",
    "customs package clearance charge",
]

JOB_SCAM = [
    "registration fee job placement",
    "training deposit job advance",
    "interview slot booking fee",
    "job offer processing charge",
    "employment verification fee",
    "joining fee MNC company",
    "background check fee advance",
    "medical test fee job",
    "ID card processing job fee",
    "uniform deposit job advance",
    "placement fee recruitment",
    "offshore job registration fee",
    "Dubai job visa processing fee",
    "foreign job placement charge",
    "Canada PR processing fee advance",
    "government job registration fee",
    "railway job application fee",
    "SSC job placement advance",
    "UPSC coaching advance deposit",
    "job security deposit refundable",
    "internship registration fee",
    "part time job advance fee",
    "online job registration charge",
    "work from home registration fee",
    "typing job advance payment",
    "data entry job fee advance",
    "job ke liye registration fee",
    "naukri registration advance bhejo",
    "company joining fee advance",
    "training fee job guarantee",
]

INVESTMENT_SCAM = [
    "profit withdrawal fee",
    "trading account activation fee",
    "crypto withdrawal processing charge",
    "stock market profit release fee",
    "investment return processing fee",
    "mutual fund withdrawal advance",
    "share market profit unlock fee",
    "forex trading withdrawal charge",
    "crypto profit tax advance",
    "demat account activation fee",
    "trading profit verification fee",
    "investment return activation charge",
    "withdrawal limit unlock fee",
    "profit transfer processing advance",
    "ROI withdrawal fee urgent",
    "Telegram investment withdrawal fee",
    "WhatsApp trading group profit fee",
    "online trading profit release",
    "stock tip profit withdrawal charge",
    "bitcoin withdrawal processing fee",
    "ethereum profit unlock fee",
    "crypto exchange verification fee",
    "trading account withdrawal advance",
    "share market profit paise bhejo",
    "crypto se nikalne ke liye fee",
    "investment wapas lene ke liye charge",
    "profit unlock karne ke liye fee",
    "trading profit release advance",
]

EMERGENCY_SCAM = [
    "hospital deposit friend emergency",
    "accident hospital advance urgent",
    "bail money friend in trouble",
    "emergency medical help advance",
    "friend accident hospital fee",
    "relative hospital deposit urgent",
    "accident victim help advance",
    "bhai accident mein hospital",
    "dost emergency mein help",
    "friend jail bail advance",
    "emergency help urgently needed",
    "medical emergency advance please",
    "ambulance charges advance",
    "ICU deposit advance urgent",
    "operation advance hospital",
    "family emergency help paise",
    "relative stuck airport advance",
    "friend stranded help urgent",
    "wallet stolen advance please",
    "purse lost help advance",
    "phone lost emergency advance",
    "stuck in city help advance",
    "bhai hospital mein advance bhejo",
    "dost accident mein paise chahiye",
    "emergency operation advance help",
    "bail ke liye paise chahiye urgent",
    "hospital ne advance manga urgent",
    "ambulance ke liye advance bhejo",
]

SCAM_CORPUS = {
    "KYC": KYC_SCAM,
    "LOTTERY": LOTTERY_SCAM,
    "TECH_SUPPORT": TECH_SUPPORT_SCAM,
    "IMPERSONATION": IMPERSONATION_SCAM,
    "JOB": JOB_SCAM,
    "INVESTMENT": INVESTMENT_SCAM,
    "EMERGENCY": EMERGENCY_SCAM,
}

ALL_FRAUD_TYPES = list(SCAM_CORPUS.keys())

# Approximate real-world distribution of scam types (based on NPCI complaint categories)
FRAUD_TYPE_WEIGHTS = {
    "KYC": 0.32,
    "IMPERSONATION": 0.22,
    "TECH_SUPPORT": 0.16,
    "LOTTERY": 0.12,
    "INVESTMENT": 0.10,
    "JOB": 0.05,
    "EMERGENCY": 0.03,
}

# Noise variants: partial matches, transliterations, misspellings
# These are appended to random scam remarks during generation to make the model harder
NOISE_SUFFIXES = [
    " please", " urgent", " asap", " ji", " bhai", " sir",
    " aaj hi", " abhi", " kal tak", " last date", " today only",
]

NOISE_PREFIXES = [
    "please ", "kindly ", "urgent ", "important ", "notice ",
]